### ISSUE TITLE
Read Environment Variables / Credentials On Client Create

### ISSUE THREAD

**Issue by dbhoot** [SigNoz/zap_otlp#9]
Currently, the `OTEL_EXPORTER_OTLP_HEADERS` variable in `zap_otlp_sync` is as a global variable at the module level.

This means if the variable is set after the application starts, the client will never be able to connect.  This happens to be the case for some environment types where we load the variables through a `local.env` on disk. 

The simple fix is to move the read of the variable into the `NewOtlpSyncer` function. Another possible solution is to pass  the headers in via map using a `WithHeaders` fuction like  `otlpmetricgrpc.WithHeaders`

Here's a patch which should be 100% backwards compatible.

```
diff --git a/zap_otlp_sync/zap_otlp_sync.go b/zap_otlp_sync/zap_otlp_sync.go
index 6e09c70..6dfeb97 100644
--- a/zap_otlp_sync/zap_otlp_sync.go
+++ b/zap_otlp_sync/zap_otlp_sync.go
@@ -20,8 +20,6 @@ import (
        "google.golang.org/protobuf/proto"
 )
 
-var otlpHeaders = os.Getenv("OTEL_EXPORTER_OTLP_HEADERS")
-
 type OtelSyncer struct {
        ctx       context.Context
        close     context.CancelFunc
@@ -71,6 +69,7 @@ func NewOtlpSyncer(conn *grpc.ClientConn, options Options) *OtelSyncer {
        }
 
        // check if there is md in the env
+       otlpHeaders := os.Getenv("OTEL_EXPORTER_OTLP_HEADERS")
        headers := map[string]string{}
        for _, header := range strings.Split(otlpHeaders, ",") {
                splittedHeader := strings.Split(header, "=")
```

**Comment by srikanthccv** [comment]
Feel free to send a pull request

**Comment by dbhoot** [comment]
@srikanthccv I tried, do not have permission.

**Comment by srikanthccv** [comment]
Please fork the repo and send PR

**Comment by dbhoot** [comment]
@srikanthccv 
https://github.com/SigNoz/zap_otlp/pull/10
